-- Create the Reviews table

CREATE TABLE IF NOT EXISTS public.reviews 
(
    review_id integer NOT NULL,
    review_text text NOT NULL,
    review_date timestamp, NOT NULL,
    inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    
)

-- Create relationship between inventory and reviews tables

-- ALTER TABLE IF EXISTS public.inventory
--     ADD CONSTRAINT fk_reviews FOREIGN KEY()

-- Create relationship between account and reviews tables


-- Insert 2 reviews into the table

INSERT INTO public.reviews
VALUES (
    1,
    '',
    2024-06-01 11:03:54,
    
    
)